### ISSUE TITLE
Replay vs Subscribe

### ISSUE THREAD

**Issue by tcoopman** [PlayingWithProjections/csharp#1]
In C# we use `Replay`, but in js `subscribe`

https://github.com/PlayingWithProjections/csharp/blob/a934652901a4fd5111173666f4ed42b5b0313d33/cli/EventStore.cs#L17 vs https://github.com/PlayingWithProjections/javascript/blob/a915479f1e1be0d89f62ab7a1fc022897be5f171/src/EventStore.js#L4

we should pick 1 and be uniform about it.

**Comment by michelgrootjans** [comment]
Solved
